// You can easily edit your project details here!
// Make sure to wrap text in quotes and don't forget the commas.

window.ABOUT_DATA = {
  "title": "Hola!<br/>I'm Afit.",
  "description": "a VFX & 3D Artist based in Jakarta, Indonesia.\n\nMy expertise lies in motion graphics, 3D FX & Animation, and VFX compositing. I strongly believe that the success of any project is rooted in great collaboration, open communication, and simply being kind.",
  "resume": "https://drive.google.com/file/d/1DIQA9XyH7Q8MbhCdcpfQfUNhiulLAtX-/view?usp=drive_link",
  "workExperience": [
    {
      "year": "Mar 2025 - Present",
      "title": "Creative Designer",
      "company": "PT. Sahabat Mikro Fintek",
      "type": "Full-Time"
    },
    {
      "year": "Current",
      "title": "Video Editor & Motion Designer",
      "company": "Freelance",
      "type": "Freelance"
    },
    {
      "year": "Jul - Oct 2024",
      "title": "Motion Graphic Designer",
      "company": "Dibilabs.Id",
      "type": "Part-Time"
    },
    {
      "year": "Feb - Jul 2024",
      "title": "Video Animator",
      "company": "PT. Telekomunikasi Indonesia",
      "type": "Internship"
    },
    {
      "year": "May - Dec 2023",
      "title": "Graphic Designer",
      "company": "AXA Mandiri Financial Services",
      "type": "Internship"
    }
  ],
  "projectExperience": [
    {
      "year": "2025",
      "title": "K-Pop Music Video",
      "company": "Blezzpost Studio",
      "type": "VFX Artist"
    },
    {
      "year": "2024",
      "title": "College 3D Animation Short",
      "company": "Politeknik Negeri Media Kreatif Jakarta",
      "type": "Project Lead, 3D Animator, FX Artist"
    }
  ]
};

window.CONTACT_DATA = {
  "title": "Hit me up!",
  "subtitle": "Ready to start your next project? Let's connect below.",
  "email": "afit14.as@gmail.com",
  "linkedin": "Afit Suradiradja",
  "linkedinUrl": "https://www.linkedin.com/in/afit-suradiradja/",
  "instagram": "@afitsrdj",
  "instagramUrl": "https://www.instagram.com/afitsrdj",
  "youtube": "Afit Suradiradja",
  "youtubeUrl": "https://youtube.com"
};

window.HOME_SLIDES = [
  {
    "id": "vfx",
    "type": "vfx",
    "eyebrow": "PORTFOLIO",
    "category": "COMPOSITING",
    "title": "VFX",
    "year": "2024",
    "role": "AFIT SURADIRADJA",
    "gradient": "linear-gradient(135deg,#0d0720 0%,#16213e 45%,#1a3a5c 80%,#0a1628 100%)",
    "vid": "https://media.afitsrdj.com/VFX_Showreel%20Web_1.mp4"
  },
  {
    "id": "3d",
    "type": "3d",
    "eyebrow": "PORTFOLIO",
    "category": "3D DESIGN",
    "title": "3D ART",
    "year": "2024",
    "role": "AFIT SURADIRADJA",
    "gradient": "linear-gradient(160deg,#0a1a0d 0%,#1b4332 45%,#2d6a4f 80%,#081c15 100%)",
    "vid": "https://media.afitsrdj.com/3D_Showreel%20Web_1.mp4"
  },
  {
    "id": "motion",
    "type": "motion",
    "eyebrow": "PORTFOLIO",
    "category": "ANIMATION",
    "title": "MOTION GRAPHICS",
    "year": "2024",
    "role": "AFIT SURADIRADJA",
    "gradient": "linear-gradient(120deg,#1c0800 0%,#3d1a00 45%,#6b3a2a 80%,#2c1408 100%)",
    "vid": "https://media.afitsrdj.com/Motion_Web_1.mp4"
  }
];

window.PORTFOLIO_ITEMS = [
  {
    "id": "new-project",
    "type": "motion, 3d",
    "eyebrow": "SAMIR",
    "category": "MOTION",
    "title": " Kenali Jenis Utang Biar Dompet Nggak Tumbang!",
    "year": "2026",
    "role": "3D & Motion Designer",
    "img": "",
    "vid": "",
    "desc": "",
    "youtube": "https://youtu.be/oYIk0hBSKSI?si=a6HjrY5Ifgkb1uOJ",
    "client": "SAMIR",
    "software": "blender, after_effects",
    "date": "2026-05-25"
  },
  {
    "id": "skor-kredit-ami",
    "type": "motion, 3d",
    "eyebrow": "SAMIR",
    "category": "MOTION",
    "title": "Skor Kredit AMI",
    "year": "2026",
    "role": "3D & Motion Designer",
    "img": "https://framerusercontent.com/images/0WpiRPcxuZt3PwSRdawkSG1iDQ.jpg",
    "desc": "A creative project for SAMIR.",
    "youtube": "https://youtu.be/RtNPeFRNIqc",
    "client": "SAMIR",
    "software": "after_effects, premiere_pro, blender",
    "vid": "https://youtu.be/RtNPeFRNIqc?si=__dp3TJ6vxO-UlVd",
    "date": "2026-02-06"
  },
  {
    "id": "new-project",
    "type": "vfx",
    "eyebrow": "BLEZZPOST STUDIO",
    "category": "MOTION",
    "title": "H1KEY - To. My First Love",
    "year": "2026",
    "role": "VFX Artist",
    "img": "",
    "vid": "https://media.afitsrdj.com/Preview%20H1KEY.mp4",
    "desc": "",
    "youtube": "https://youtu.be/sBx08M4cDME?si=BrcI2okKopzSgqrM",
    "software": "after_effects, mocha",
    "client": "Blezzpost Studio",
    "date": "2026-01-31"
  },
  {
    "id": "videotron-samir",
    "type": "vfx, motion",
    "eyebrow": "SAMIR",
    "category": "MOTION",
    "title": "Videotron SAMIR",
    "year": "2026",
    "role": "VFX Artist",
    "img": "https://framerusercontent.com/images/0oKYWHvzgXRpteR8y0rNk0S2r4.jpg",
    "desc": "Videotron campaign for SAMIR.",
    "youtube": "https://youtu.be/xPB954pmRFw",
    "client": "SAMIR",
    "software": "after_effects",
    "date": "2026-01-03"
  },
  {
    "id": "new-project",
    "type": "vfx",
    "eyebrow": "BLEZZPOST STUDIO",
    "category": "MOTION",
    "title": "Waker Like That",
    "year": "2025",
    "role": "3D & VFX Artist",
    "img": "",
    "vid": "https://media.afitsrdj.com/Preview%20Waker(1).mp4",
    "desc": "",
    "youtube": "https://youtu.be/ekQrIXjp2oA?si=XtJQzC7XtIE1Ozst",
    "client": "Blezzpost Studio",
    "software": "after_effects, mocha, blender",
    "date": "2025-12-24"
  },
  {
    "id": "new-project",
    "type": "vfx",
    "eyebrow": "BLEZZPOST STUDIO",
    "category": "MOTION",
    "title": "NTX - Ice Luv",
    "year": "2025",
    "role": "VFX Artist",
    "img": "",
    "vid": "https://media.afitsrdj.com/Preview%20NTX.mp4",
    "desc": "",
    "youtube": "https://youtu.be/nNjabw6ybnQ?si=CxyzwiaVLN8ErpbV",
    "client": "Blezzpost Studio",
    "software": "after_effects, blender",
    "date": "2025-12-08"
  },
  {
    "id": "new-project",
    "type": "vfx",
    "eyebrow": "BLEZZPOST STUDIO",
    "category": "MOTION",
    "title": "Xodiac - Alibi",
    "year": "2025",
    "role": "VFX Artist",
    "img": "",
    "vid": "https://media.afitsrdj.com/Preview%20Xodiac.mp4",
    "desc": "",
    "youtube": "https://youtu.be/4qdoevwJnOE?si=dtg2o0XlcaVlrUHD",
    "client": "Blezzpost Studio",
    "software": "after_effects",
    "date": "2025-11-20"
  },
  {
    "id": "motion-reel",
    "type": "motion",
    "eyebrow": "PERSONAL",
    "category": "MOTION",
    "title": "Motion Reel",
    "year": "2025",
    "role": "Motion Designer",
    "img": "https://framerusercontent.com/images/QlHF5Lp9xONQXIuix0cZeV1bQ.jpg",
    "desc": "Personal motion graphics showreel.",
    "youtube": "https://youtu.be/w0Sxz2GFe44",
    "client": "Personal",
    "software": "after_effects",
    "date": "2025-02-06"
  },
  {
    "id": "hang-tuah",
    "type": "3d, motion",
    "eyebrow": "COLLEGE",
    "category": "3D",
    "title": "Hang Tuah & Hang Jebat",
    "year": "2025",
    "role": "3D Artist",
    "vid": "https://framerusercontent.com/assets/D2ClrMCVzMAvCXNHR3Go7obANjQ.mp4",
    "desc": "Short 2D/3D animation project for Polimedia.",
    "youtube": "https://youtu.be/mRFGpTaDG34",
    "client": "Polimedia",
    "software": "maya, blender, after_effects",
    "date": "2025-01-03"
  },
  {
    "id": "djavu",
    "type": "motion",
    "eyebrow": "PERSONAL",
    "category": "MOTION",
    "title": "DJAVU Logo Motion",
    "year": "2024",
    "role": "Motion Designer",
    "vid": "https://framerusercontent.com/assets/jpCkaZu8r5RzCXoYngvhO8OBOU.mp4",
    "desc": "Logo motion design for DJAVU Creative.",
    "client": "Personal",
    "software": "after_effects",
    "date": "2024-10-28"
  },
  {
    "id": "rigid-body",
    "type": "3d",
    "eyebrow": "COLLEGE",
    "category": "3D",
    "title": "Rigid Body Sim",
    "year": "2024",
    "role": "3D Artist",
    "vid": "https://framerusercontent.com/assets/RKclWjZkdQRRQiJKSM5CPFZZOMM.mp4",
    "desc": "Rigid body simulation and texturing in Autodesk Maya.",
    "youtube": "https://youtu.be/dZyIAHOZef0",
    "client": "Polimedia",
    "software": "maya, blender",
    "date": "2024-09-27"
  },
  {
    "id": "windmill",
    "type": "3d",
    "eyebrow": "PERSONAL",
    "category": "3D",
    "title": "Windmill",
    "year": "2024",
    "role": "3D Artist",
    "vid": "https://framerusercontent.com/assets/s1FKfEjlCpWgZfPid5Qw6KaY.mp4",
    "desc": "3D windmill artwork.",
    "client": "Personal",
    "software": "maya",
    "date": "2024-08-24"
  },
  {
    "id": "adjuice",
    "type": "motion",
    "eyebrow": "FREELANCE",
    "category": "MOTION",
    "title": "Adjuice Social Media",
    "year": "2024",
    "role": "Motion Designer",
    "vid": "https://framerusercontent.com/assets/UyMTkzhIYR6KOcZL4WauavdM940.mp4",
    "desc": "Social media motion graphics for Adjuice.",
    "client": "Adjuice",
    "software": "after_effects",
    "date": "2024-07-21"
  },
  {
    "id": "videolearning",
    "type": "motion",
    "eyebrow": "TELKOM",
    "category": "MOTION",
    "title": "Video Learning",
    "year": "2024",
    "role": "Motion Designer",
    "vid": "https://framerusercontent.com/assets/OML9YKq80RWEamXPQDaYw2GfTss.mp4",
    "desc": "Video learning materials for Telkom CorpU.",
    "client": "PT. Telekomunikasi Indonesia",
    "software": "after_effects, premiere_pro",
    "date": "2024-06-18"
  },
  {
    "id": "gizzi-susu",
    "type": "motion",
    "eyebrow": "DIBILABS",
    "category": "MOTION",
    "title": "Motion Gizzi",
    "year": "2024",
    "role": "Motion Designer",
    "vid": "https://framerusercontent.com/assets/yQS73UK6MexGaktmfEkqPohP4X8.mp4",
    "desc": "Motion graphics for Gizzi UHT.",
    "client": "Dibilabs.Id",
    "software": "after_effects",
    "date": "2024-05-15"
  },
  {
    "id": "hut-ri",
    "type": "motion",
    "eyebrow": "FREELANCE",
    "category": "VFX",
    "title": "Parade HUT RI",
    "year": "2024",
    "role": "Video Editor",
    "vid": "https://framerusercontent.com/assets/qfW0xlf9we7HDXhp0XjWPuBa3E.mp4",
    "desc": "Video editing for Independence Day parade.",
    "client": "Freelance",
    "software": "davinci_resolve",
    "date": "2024-04-12"
  },
  {
    "id": "3d-showreel",
    "type": "3d",
    "eyebrow": "PERSONAL",
    "category": "3D",
    "title": "3D Showreel",
    "year": "2024",
    "role": "3D Artist",
    "vid": "https://framerusercontent.com/assets/7SejrHjAR0gemdXw1c2EQ2NujQ.mp4",
    "desc": "Compilation of my 3D artwork.",
    "youtube": "https://youtu.be/Sk_Uw_BpRTY",
    "client": "Personal",
    "software": "blender, maya, after_effects",
    "date": "2024-03-09"
  },
  {
    "id": "gita23rd",
    "type": "motion",
    "eyebrow": "FREELANCE",
    "category": "MOTION",
    "title": "Gita 23rd Birthday",
    "year": "2024",
    "role": "Video Editor",
    "vid": "https://framerusercontent.com/assets/XqAmC8E5WacMTftstK5DNlG2HP8.mp4",
    "desc": "Fan video for JKT48 member.",
    "client": "Freelance",
    "software": "after_effects",
    "date": "2024-02-06"
  },
  {
    "id": "aftermovie",
    "type": "vfx",
    "eyebrow": "HIMA Animasi",
    "category": "VFX",
    "title": "Aftermovie POK7",
    "year": "2024",
    "role": "Video Editor",
    "vid": "https://framerusercontent.com/assets/hGTnvE3DoTPNnjBMdtAmdiaToA4.mp4",
    "desc": "Documentation Aftermovie editing for Parade Otak Kanan 7.",
    "youtube": "https://youtu.be/iIQyqquAgIg",
    "client": "HIMA Animasi",
    "software": "premiere_pro, after_effects",
    "date": "2024-01-03"
  },
  {
    "id": "catjipiti",
    "type": "motion",
    "eyebrow": "AXA MANDIRI",
    "category": "MOTION",
    "title": "Catjipiti AXA Mandiri",
    "year": "2023",
    "role": "Motion Designer",
    "vid": "https://framerusercontent.com/assets/CbkkKnTXQZc7I359a6NR4Be2aRo.mp4",
    "desc": "Social media feeds design and motion for AXA Mandiri.",
    "client": "AXA Mandiri",
    "software": "after_effects, photoshop",
    "date": "2023-04-12"
  },
  {
    "id": "railways",
    "type": "vfx",
    "eyebrow": "PERSONAL",
    "category": "VFX",
    "title": "The Railways",
    "year": "2023",
    "role": "Colorist",
    "vid": "https://framerusercontent.com/assets/cwES02aAV0MPRlhO1y2bXF5rs.mp4",
    "desc": "Color grading experiment with Davinci Resolve.",
    "client": "Personal",
    "software": "davinci_resolve",
    "date": "2023-03-09"
  },
  {
    "id": "axa-tm",
    "type": "motion",
    "eyebrow": "AXA MANDIRI",
    "category": "MOTION",
    "title": "AXA Motivational",
    "year": "2023",
    "role": "Motion Designer",
    "vid": "https://framerusercontent.com/assets/NVedGjtN0Jug9NBkDKGaAp4YEs.mp4",
    "desc": "Opening video for telemarketing motivational event.",
    "client": "AXA Mandiri",
    "software": "after_effects",
    "date": "2023-02-06"
  },
  {
    "id": "showreel-edit",
    "type": "motion",
    "eyebrow": "PERSONAL",
    "category": "MOTION",
    "title": "Showreel 2023",
    "year": "2023",
    "role": "Motion Designer / Video Editor",
    "vid": "https://framerusercontent.com/assets/QkC1RcqN2rogPpOggxw7rHhwFUA.mp4",
    "desc": "Video editing and motion graphics showreel.",
    "youtube": "https://youtu.be/xMXOH_fMANg",
    "client": "Personal",
    "software": "after_effects, premiere_pro",
    "date": "2023-01-03"
  },
  {
    "id": "bts-photo",
    "type": "vfx",
    "eyebrow": "PERSONAL",
    "category": "VFX",
    "title": "BTS Photoshoot",
    "year": "2022",
    "role": "Video Editor",
    "vid": "https://framerusercontent.com/assets/QRcUQSCGpzMaL1IapHhJ7cU44.mp4",
    "desc": "Behind the scenes photoshoot documentation.",
    "youtube": "https://youtu.be/M4-RdMb5Jg4",
    "client": "Personal",
    "software": "premiere_pro",
    "date": "2022-01-03"
  }
];
